Interfacebuild
Vuictorovna/climate-change-action-assistant pull request #2
Opened 2023-09-13 08:29 UTC by jdc338

2023-09-13 13:19 UTC, Vuictorovna requested changes
Good job! I briefly glanced at your code. 
It looks quite good. But maybe you need to take a look for this : you are re-initializing the session state every time the script runs. This will reset the chat history. The session state should ideally only be initialized once if it hasn't been initialized before.

2023-09-13 13:19 UTC, Vuictorovna commented on requirements.txt
> +pip install streamlit
Please update the requirements.txt file to include only the package names and versions, such as streamlit==x.y.z, rather than command-line instructions like pip install streamlit. This keeps the file clean and directly usable by package managers

2023-09-13 13:56 UTC, Vuictorovna approved these changes

2023-09-13 13:57 UTC, merged

2023-09-14 07:47 UTC, jdc338 commented
> Good job! I briefly glanced at your code. It looks quite good. But maybe you need to take a look for this : you are re-initializing the session state every time the script runs. This will reset the chat history. The session state should ideally only be initialized once if it hasn't been initialized before.

James: 'Great catch Volha! Will update this now"